import os
import torch
import numpy as np
import threading
from typing import Dict
from kokoro import KPipeline

class TTSEngine:
    def __init__(self):
        self.device = 'cuda' if torch.cuda.is_available() else 'cpu'
        print(f"Initializing TTSEngine on device: {self.device}")
        
        # Cache for pipelines by language code
        self.pipelines: Dict[str, KPipeline] = {}
        self.lock = threading.Lock()
        
        # Initialize default pipeline (American English 'a')
        self._get_pipeline('a')

    def _get_pipeline(self, lang_code: str) -> KPipeline:
        lang_code = lang_code.lower()
        if lang_code not in self.pipelines:
            # Share the model between different language pipelines if one already exists
            model = None
            if self.pipelines:
                model = list(self.pipelines.values())[0].model
            
            print(f"Loading pipeline for lang_code: {lang_code} (model shared: {model is not None})")
            # If no model exists yet, KPipeline will create it. If one does, it reuses it.
            self.pipelines[lang_code] = KPipeline(
                lang_code=lang_code,
                device=self.device,
                model=model or True
            )
        return self.pipelines[lang_code]

    def synthesize(self, text: str, voice: str, speed: float, lang_code: str) -> bytes:
        import io
        import soundfile as sf
        
        # Lock to ensure only one thread executes the heavy inference at a time
        with self.lock:
            pipeline = self._get_pipeline(lang_code)
            generator = pipeline(text, voice=voice, speed=speed)
            
            audio_segments = []
            for _, _, audio in generator:
                if audio is not None:
                    if hasattr(audio, 'cpu'):
                        audio = audio.cpu().numpy()
                    elif hasattr(audio, 'numpy'):
                        audio = audio.numpy()
                    audio_segments.append(audio)
            
            if not audio_segments:
                raise ValueError("No audio was generated by the pipeline.")
                
            full_audio = np.concatenate(audio_segments)
            
            # Write to in-memory WAV bytes
            wav_io = io.BytesIO()
            sf.write(wav_io, full_audio, 24000, format='WAV', subtype='PCM_16')
            return wav_io.getvalue()

# Singleton instance
tts_engine = TTSEngine()
